function(check_packages)
    message( ">> 第三方库")
    get_cmake_property(_variableNames VARIABLES)
    foreach (_variableName ${_variableNames})
        if (_variableName MATCHES "^[A-Za-z].*_FOUND")
            string(REPLACE "_FOUND" "" _variableName ${_variableName})
            message(\t\t "√ ${_variableName}")
        endif()
    endforeach()
endfunction()
